### ISSUE TITLE
Alterar script python para ler txt e enviar mensagem para o servidor web

### ISSUE THREAD

**Issue by thlindustries** [thlindustries/watchdogs#1]
Passos:
1. Ler um arquivo txt em python.
2. Transformar o conteúdo de dentro do arquivo txt em variáveis.
3. Integrar esse script com o script do SimulatedData.py.
4. Testar o envio da variável para o servidor web.

**Comment by gabrielroodriz** [comment]
Script de leitura file txt desenvolvido, armazenando os dados em variáveis e enviando para o HubIot
